import{a as q,S as P,i as c}from"./assets/vendor-Db2TdIkw.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const I="49627049-8ac1639d7a1db97b4097e2b9b",A="https://pixabay.com/api/";async function f(e,s=1){try{return(await q.get(A,{params:{key:I,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}})).data}catch(o){throw console.error("Error fetching images: ",o),o}}let u;function y(e,s){const o=document.querySelector(".gallery"),n=e.map(({webformatURL:t,largeImageURL:r,tags:l,likes:b,views:v,comments:S,downloads:w})=>`
        <li class="gallery-item">
          <a href="${r}">
            <img class="gallery-img" src="${t}" alt="${l}" />
            <div class="info">
              <p class="info-item"><b>Likes:</b> ${b}</p>
              <p class="info-item"><b>Views:</b> ${v}</p>
              <p class="info-item"><b>Comments:</b> ${S}</p>
              <p class="info-item"><b>Downloads:</b> ${w}</p>
            </div>
          </a>
        </li>`).join("");o.insertAdjacentHTML("beforeend",n),u?u.refresh():u=new P(".gallery a"),document.querySelectorAll(".gallery-item").length}function M(){const e=document.querySelector(".gallery");e.innerHTML=""}function h(){document.querySelector(".load-more-wrapper .loader").classList.remove("hidden")}function p(){document.querySelector(".load-more-wrapper .loader").classList.add("hidden")}function L(){const e=document.querySelector(".load-more");e.classList.remove("hidden"),e.classList.add("is-visible")}function $(){const e=document.querySelector(".load-more");e.classList.remove("is-visible"),e.classList.add("hidden")}const E=document.querySelector(".form"),H=document.querySelector('input[name="search-text"]'),g=document.querySelector(".load-more");let m="",d=1,a=0;E.addEventListener("submit",async e=>{e.preventDefault();const s=H.value.trim();if(!s){c.warning({message:"Please enter a search term!",position:"topRight"});return}m=s,d=1,a=0,$(),i.classList.remove("hidden"),i.classList.add("visible"),M(),h();try{const o=await f(m,d);a=o.totalHits,o.hits.length===0?c.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):(y(o.hits,a),document.querySelectorAll(".gallery-item").length<a&&L())}catch{c.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p(),i.classList.remove("visible"),i.classList.add("hidden")}});const i=document.querySelector(".loading-message");g.addEventListener("click",async()=>{d+=1,g.classList.add("hidden"),i.classList.remove("hidden"),i.classList.add("visible"),h(),setTimeout(async()=>{try{const e=await f(m,d);a=e.totalHits,e.hits.length===0?c.error({message:"Sorry, no images found. Please try a different search.",position:"topRight"}):(y(e.hits,a),document.querySelectorAll(".gallery-item").length<a&&L())}catch{c.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p(),i.classList.remove("visible"),i.classList.add("hidden")}},2e3)});
//# sourceMappingURL=index.js.map
