import{a as P,S as I,i as l}from"./assets/vendor-Db2TdIkw.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const A="49627049-8ac1639d7a1db97b4097e2b9b",B="https://pixabay.com/api/";async function f(e,s=1){try{return(await P.get(B,{params:{key:A,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}})).data}catch(r){throw console.error("Error fetching images: ",r),r}}let u;function y(e,s){const r=document.querySelector(".gallery"),a=e.map(({webformatURL:t,largeImageURL:o,tags:n,likes:S,views:v,comments:q,downloads:w})=>`
        <li class="gallery-item">
          <a href="${o}">
            <img class="gallery-img" src="${t}" alt="${n}" />
            <div class="info">
              <p class="info-item"><b>Likes:</b> ${S}</p>
              <p class="info-item"><b>Views:</b> ${v}</p>
              <p class="info-item"><b>Comments:</b> ${q}</p>
              <p class="info-item"><b>Downloads:</b> ${w}</p>
            </div>
          </a>
        </li>`).join("");r.insertAdjacentHTML("beforeend",a),u?u.refresh():u=new I(".gallery a"),document.querySelectorAll(".gallery-item").length}function E(){const e=document.querySelector(".gallery");e.innerHTML=""}function h(){document.querySelector(".load-more-wrapper .loader").classList.remove("hidden")}function p(){document.querySelector(".load-more-wrapper .loader").classList.add("hidden")}function b(){const e=document.querySelector(".load-more");e.classList.remove("hidden"),e.classList.add("is-visible")}function L(){const e=document.querySelector(".load-more");e.classList.remove("is-visible"),e.classList.add("hidden")}const M=document.querySelector(".form"),R=document.querySelector('input[name="search-text"]'),g=document.querySelector(".load-more");let m="",d=1,i=0;M.addEventListener("submit",async e=>{e.preventDefault();const s=R.value.trim();if(!s){l.warning({message:"Please enter a search term!",position:"topRight"});return}m=s,d=1,i=0,L(),E(),h();try{const r=await f(m,d);i=r.totalHits,r.hits.length===0?l.error({message:"Sorry, no images found. Please try a different search.",position:"topRight"}):(y(r.hits,i),document.querySelectorAll(".gallery-item").length<i&&b())}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p()}});const c=document.querySelector(".loading-message");g.addEventListener("click",async()=>{d+=1,g.classList.add("hidden"),c.classList.remove("hidden"),c.classList.add("visible"),h();try{const e=await f(m,d);y(e.hits,i);const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=i?(L(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch{l.error({message:"Error loading more images.",position:"topRight"})}finally{p(),c.classList.remove("visible"),c.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
